id: A8790F503
title: Method of Confession based on the Four Powers
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:02:16.911017
  last_modified_at: 2022-03-01 01:02:16.911024
